# Generated by Django 5.2.1 on 2025-08-04 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_estimate_user_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estimate_user_year',
            new_name='EstimateUserYear',
        ),
    ]
