# Generated by Django 5.2.4 on 2025-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_estimateuseryear_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomputedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='estimateuseryear',
            unique_together=set(),
        ),
    ]
