# Generated by Django 5.2.1 on 2025-07-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalc', '0001_initial'),
        ('scheduler', '0004_alter_courseevent_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentgrade',
            options={'ordering': ['course_event__event_type']},
        ),
        migrations.RemoveField(
            model_name='assessmentgrade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coursegrade',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='gpa_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scheduler.course'),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterModelTable(
            name='assessmentgrade',
            table='gpacalc_assessmentgrade',
        ),
        migrations.AlterModelTable(
            name='coursegrade',
            table='gpacalc_coursegrade',
        ),
    ]
