# Generated by Django 5.2.4 on 2025-07-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalc', '0002_alter_assessmentgrade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegrade',
            name='credits',
        ),
    ]
