# Generated by Django 5.2.1 on 2025-07-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalc', '0004_gpacalcprogress'),
        ('scheduler', '0011_alter_courseevent_days_alter_courseevent_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWeightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.courseevent')),
            ],
            options={
                'db_table': 'gpacalc_assessmentweightage',
            },
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='scheduler.course')),
            ],
            options={
                'db_table': 'gpacalc_gradingscheme',
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='GradeScale',
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='achieved_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='course_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.courseevent'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='course_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpacalc.coursegrade'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='weightage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='assessmentweightage',
            name='grading_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightages', to='gpacalc.gradingscheme'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentweightage',
            unique_together={('grading_scheme', 'course_event')},
        ),
    ]
