# Generated by Django 5.2.1 on 2025-07-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalc', '0004_gpacalcprogress'),
        ('scheduler', '0010_course_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='scheduler.course')),
            ],
            options={
                'db_table': 'gpacalc_gradingscheme',
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentWeightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_weightages', to='scheduler.courseevent')),
                ('grading_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightages', to='gpacalc.gradingscheme')),
            ],
            options={
                'db_table': 'gpacalc_assessmentweightage',
                'unique_together': {('grading_scheme', 'course_event')},
            },
        ),
    ]
