# Generated by Django 5.2.4 on 2025-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalc', '0005_gradingscheme_assessmentweightage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeScale',
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
