# Generated by Django 5.2.4 on 2025-07-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpacalc', '0006_delete_gradescale_alter_coursegrade_letter_grade'),
        ('scheduler', '0010_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentgrade',
            name='achieved_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='course_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.courseevent'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='course_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpacalc.coursegrade'),
        ),
        migrations.AlterField(
            model_name='assessmentgrade',
            name='weightage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentweightage',
            name='course_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.courseevent'),
        ),
    ]
