# Generated by Django 5.2.1 on 2025-07-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course')),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
