# Generated by Django 5.2.1 on 2025-07-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_courseevent_course_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='scheduler.course'),
        ),
    ]
