# Generated by Django 5.2.1 on 2025-07-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_event_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.course'),
        ),
    ]
