# Generated by Django 5.2.4 on 2025-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_courseevent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='times',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
