# Generated by Django 5.2.4 on 2025-07-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_event_days_event_end_date_event_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='days',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='times',
            field=models.CharField(max_length=100),
        ),
    ]
