# Generated by Django 5.2.4 on 2025-07-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_event_days_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_type', 'course_code', 'section_number')},
        ),
    ]
