# Generated by Django 5.2.4 on 2025-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_event_dates_event_days_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
