# Generated by Django 5.2.1 on 2025-07-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseevent',
            name='days',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='courseevent',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='dates',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='days',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
