# Generated by Django 5.2.4 on 2025-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_course_has_events_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictFreeSchedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_term', models.CharField(db_index=True, max_length=20)),
                ('courses', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_free', models.JSONField(help_text='List of conflict-free schedules')),
            ],
        ),
    ]
