# Generated by Django 5.2.4 on 2025-08-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_conflictfreeschedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegPlannerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('typically_offered_fall', models.BooleanField(default=False)),
                ('typically_offered_winter', models.BooleanField(default=False)),
                ('typically_offered_summer', models.BooleanField(default=False)),
                ('restrictions', models.TextField(blank=True, null=True)),
                ('offerings', models.TextField(blank=True, null=True)),
                ('prerequisites_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deg_planner_courses',
            },
        ),
        migrations.CreateModel(
            name='DegPlannerProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('is_coop', models.BooleanField(default=False)),
                ('total_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_requirements', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deg_planner_programs',
            },
        ),
        migrations.CreateModel(
            name='DegPlannerProgramSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=500)),
                ('semester_order', models.IntegerField()),
                ('course_code', models.CharField(max_length=200)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_elective_category', models.BooleanField(default=False)),
                ('elective_category', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='scheduler.degplannerprogram')),
            ],
            options={
                'db_table': 'deg_planner_program_sequence',
                'ordering': ['semester_order'],
            },
        ),
        migrations.CreateModel(
            name='DegPlannerPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(default='mandatory', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='scheduler.degplannercourse')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='scheduler.degplannercourse')),
            ],
            options={
                'db_table': 'deg_planner_prerequisites',
                'unique_together': {('course', 'prerequisite')},
            },
        ),
        migrations.CreateModel(
            name='DegPlannerProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_requirements', to='scheduler.degplannercourse')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='scheduler.degplannerprogram')),
            ],
            options={
                'db_table': 'deg_planner_program_requirements',
                'unique_together': {('program', 'course')},
            },
        ),
    ]
