# Generated by Django 5.2.1 on 2025-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0002_useryearestimate_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useryearestimate',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
