# Generated by Django 5.2.1 on 2025-07-12 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0003_alter_useryearestimate_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useryearestimate',
            unique_together={('offered_term', 'user', 'session')},
        ),
    ]
