# Generated by Django 5.2.1 on 2025-07-12 21:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0004_alter_useryearestimate_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useryearestimate',
            unique_together={('offered_term', 'user')},
        ),
    ]
