# Generated by Django 5.2.1 on 2025-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0005_alter_useryearestimate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appclick',
            name='average_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
