# Generated by Django 5.2.1 on 2025-07-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0007_appsession_delete_appclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
