# Generated by Django 5.2.1 on 2025-07-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0008_alter_appsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SectionView',
        ),
    ]
