# Generated by Django 5.2.1 on 2025-07-12 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0009_appsession_section_name_delete_sectionview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appsession',
            unique_together={('user', 'app_name', 'session_id', 'section_name')},
        ),
    ]
