# Generated by Django 5.2.1 on 2025-07-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogger', '0011_apitiminglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitiminglog',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
