# Generated by Django 5.2.4 on 2025-07-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
