# Generated by Django 5.2.4 on 2025-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopforum', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
