# Generated by Django 5.2.4 on 2025-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopforum', '0004_alter_post_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='major',
            field=models.CharField(blank=True, help_text='Student major or field of study', max_length=100, null=True),
        ),
    ]
